apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: mongoserver
  name: mongoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongoserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        io.kompose.service: mongoserver
    spec:
      containers:
        - image: mongo
          name: mongoserver
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
