apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: node-service
  name: node-service
spec:
  ports:
    - name: "19031"
      port: 19031
      targetPort: 19031
  selector:
    io.kompose.service: node-service
status:
  loadBalancer: {}
