apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: pythonservice
  name: pythonservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pythonservice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        io.kompose.service: pythonservice
    spec:
      containers:
        - args:
            - python
            - -u
            - manage.py
            - runserver
            - 0.0.0.0:19034
          env:
            - name: ALLOWED_HOSTS
              value: '[''*'',]'
          image: epsilonsp22/pythonservice:latest
          name: pythonservice
          ports:
            - containerPort: 19034
          resources: {}
          volumeMounts:
            - mountPath: /msvc-python/files
              name: files
      restartPolicy: Always
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: files
status: {}
