---
kind: Service
apiVersion: v1
metadata:
  name: redis-server-service
spec:
  selector:
    app: redis-server
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 6379
      # Port to forward to inside the pod
      targetPort: 6379
      # Port accessible outside cluster
      nodePort: 31001
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
        - name: redis-server
          image: redis
          ports:
          - containerPort: 6379
          resources: 
            requests:
              cpu: 200m
              memory: 128M
            limits:
              cpu: 500m
              memory: 256M
      restartPolicy: Always