apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: redis-server
  name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        io.kompose.service: redis-server
    spec:
      containers:
        - image: redis
          name: redis-server
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
