apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: users-service
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        io.kompose.service: users-service
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://admin:admin@localhost:5432/epsilon
            - name: NODE_ENV
            - name: TOKEN_SECRET
              value: changeme
          image: epsilonsp22/users-service:latest
          name: users-service
          ports:
            - containerPort: 19032
          resources: {}
        - env:
          - name: POSTGRES_PASSWORD
            value: admin
          - name: POSTGRES_USER
            value: admin
          image: epsilonsp22/users-db:latest
          name: users-db
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
