# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
          name: Build and push to docker
          command: |
            docker build -t epsilonsp22/users-service .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push epsilonsp22/users-service:latest
      - run:    
          name: Fix Ssh Could not resolve hostname
          command: ssh-keyscan 149.165.153.71 >> ~/.ssh/known_hosts
      
      - add_ssh_keys:
          fingerprints:
            - "98:38:1f:3f:9d:1b:2a:79:8b:27:9e:06:7a:cc:de:f6"
      - run:
          name: Deployment
          command: |
            ssh ubuntu@149.165.153.71 'cd epsilon/kubes_amd/ && git pull && kubectl delete deployment --ignore-not-found=true msvc-users && kubectl delete service --ignore-not-found=true users-service && kubectl apply -f users-kube.yml'

      
