---
kind: Service
apiVersion: v1
metadata:
  name: mongo-services
spec:
  selector:
    app: mongo-db
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 27017
      # Port to forward to inside the pod
      targetPort: 27017
      # Port accessible outside cluster
      nodePort: 31002
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - image: mongo
          name: mongo-db
          ports:
            - containerPort: 27017
          resources: 
            requests:
               cpu: 200m
               memory: 128M
            limits:
               cpu: 300m
               memory: 256M
      restartPolicy: Always