apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: files
  name: files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
status: {}
