---
kind: Service
apiVersion: v1
metadata:
  name: kafka-services
spec:
  selector:
    app: kafka
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 9092
      # Port to forward to inside the pod
      targetPort: 9092
      # Port accessible outside cluster
      #nodePort: 30004
  #type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-services:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-services:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          tty: true
          resources: 
            requests:
               cpu: '300m'
               memory: '512M'
            limits:
               cpu: '600m'
               memory: '1024M'
      restartPolicy: Always